utils::globalVariables(c("begin_date", "end_date", "judge",
                         "discipline", "representing", "given_name",
                         "surname", "subtitle", "number", "time", "code",
                         "external_id", "date_of_birth", "sex", "ranked", "team",
                         "team_rank", "team_mark", "stage", "group_number",
                         "performance_number", "routine_number",
                         "name", "event_uuid", "unique_person", "x",
                         "given_panel_name", "sport", "event_id",
                         "link_start", "link_end", "competition", "unique_id",
                         "country", "club", "en_name", "name_1", "club_1", "country_1"))
